from flask import (
    Flask,
    request,
    render_template,
    redirect,
    url_for,
    send_from_directory,
)
from tatoeba_adapter import get_translations

app = Flask(__name__)


# Index page
@app.route("/")
def base():
    return send_from_directory("client/public", "index.html")


# Serve static files generated by Svelte
@app.route("/<path:path>")
def static_files(path):
    return send_from_directory("client/public", path)


@app.route("/api/v0/translations", methods=["GET"])
def api_v0():
    if any([kw not in request.args for kw in ["query", "lang_from", "lang_to"]]):
        return "Invalid arguments", 400

    return get_translations(
        query=request.args["query"],
        lang_from=request.args["lang_from"],
        lang_to=request.args["lang_to"],
        find_similar=request.args["find_similar"] == "true",
    )


# TODO: instead of making api calls, download database export and make calls there
@app.route("/api/v1/translations", methods=["GET"])
def api_v1():
    raise NotImplementedError
