from wgcompany_scraper import load_ads_from_file
from flask import (
    Flask,
    request,
    render_template,
    redirect,
    url_for,
    send_from_directory,
)

app = Flask(__name__)


# Index page
@app.route("/")
def base():
    return send_from_directory("client/public", "index.html")


@app.route("/archive")
def archive():
    raise NotImplementedError


# Serve static files generated by Svelte
@app.route("/<path:path>")
def static_files(path):
    return send_from_directory("client/public", path)


@app.route("/api/v0/ads", methods=["GET"])
def api_v0():
    ads = load_ads_from_file("archive.json")
    return list(ads.values())
